#!/bin/bash

set -xe

DOCKER_CONTEXT=default
STATUS=test
REVISION=${1:-0}
VERSION="1.0.${REVISION}"
echo "Deployment version $VERSION"

# Try to obtain local IVY configuration, use public repo otherwise
test -f ivysettings.xml || wget http://jenkins.mi.cardcontact.de/ivysettings.xml || true

create_service() {
    SRV=$1
    TARNAME=$2
    NAME=$3

    cd tls
    ./issue-cert ${SRV}-${STATUS}

    cd ../${SRV}
    ant clean

    mkdir -p etc/tls
    cp ../tls/truststore.p12 etc/tls

    rm -f etc/tls/keystore.p12
    cat ../tls/key/prk_${SRV}-${STATUS}.pem ../tls/newcerts/cert_${SRV}-${STATUS}.pem ../tls/cert_system_ca.pem >client.pem
    openssl pkcs12 -export -out etc/tls/keystore.p12 -in client.pem -name server --passout pass:password
    chmod 644 etc/tls/keystore.p12
    rm client.pem

    if [ -d "../tas" ]; then
        cp -r ../tas etc/tas
    fi

    ant -Dunpack-fs=1
    tar xzf ${TARNAME}.tgz --strip-components=1
    rm ${TARNAME}.tgz
    chmod +x ${NAME}
    docker --context $DOCKER_CONTEXT build -t ${SRV}-${STATUS} .
    cd ..
}

cd nginx
docker --context $DOCKER_CONTEXT build -t nginx-${STATUS} .
cd ..

# Create fresh truststore
cd tls
./issue-cert client v3_req_tls_client
rm -f truststore.p12
keytool -import -keystore truststore.p12 -noprompt -file cert_root_ca.pem -alias rootca -storepass password
keytool -import -keystore truststore.p12 -noprompt -file cert_system_ca.pem -alias systemca -storepass password
chmod 644 truststore.p12
cd ..

cd pkiaas
ant clean

mkdir -p etc/tls
cp ../tls/truststore.p12 etc/tls
rm -f etc/tls/clientkeystore.p12
cat ../tls/key/prk_client.pem ../tls/newcerts/cert_client.pem >client.pem
openssl pkcs12 -export -out etc/tls/clientkeystore.p12 -in client.pem -name client --passout pass:password
chmod 644 etc/tls/clientkeystore.p12
rm client.pem

if [ -d "../tas" ]; then
        cp -r ../tas etc/tas
fi

ant -Dunpack-fs=1 -Dversion=$VERSION
chmod +x scriptingserver
docker --context $DOCKER_CONTEXT build -t pkiaas-${STATUS} .
cd ..

create_service pkiaas-backend pki-as-a-service-backend start-service
