services:
  mariadb-test:
      environment:
          - MARIADB_AUTO_UPGRADE=1
          - MARIADB_DATABASE=pkiaas
          - MARIADB_ROOT_PASSWORD=changeme
          - MARIADB_USER=pkiaas
          - MARIADB_PASSWORD=changeme
      healthcheck:
          test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
          start_period: 10s
          interval: 10s
          timeout: 5s
          retries: 3
      volumes:
          - dbdata:/var/lib/mysql
      container_name: mariadb-test
      image: mariadb

  pkiaas-backend-test:
      container_name: pkiaas-backend-test
      image: pkiaas-backend-test
      depends_on:
          mariadb-test:
              condition: service_healthy
      environment:
          - DATABASE_URL=jdbc:mariadb://mariadb-test/pkiaas
          - DATABASE_USER=pkiaas
          - DATABASE_PASSWORD=changeme

  pkiaas-test:
      container_name: pkiaas-test
      image: pkiaas-test
      depends_on:
          mariadb-test:
              condition: service_healthy
      environment:
          - DATABASE_URL=jdbc:mariadb://mariadb-test/pkiaas
          - DATABASE_USER=pkiaas
          - DATABASE_PASSWORD=changeme
          - SERVER_URL=http://localhost:8080
          - SERVICE_SCOPE=test

  nginx-test:
      container_name: nginx-test
      image: nginx-test
      depends_on:
        pkiaas-backend-test:
            condition: service_started
        pkiaas-test:
            condition: service_started
      ports:
          - "8080:8080"

volumes:
  dbdata:
