# Server configuration

server.ports=mainport,tlsport
server.mainport.port=8080
server.mainport.host=0.0.0.0

server.tlsport.port = 8443
server.tlsport.host = 0.0.0.0
server.tlsport.keystore = etc/tls/keystore.p12
server.tlsport.keystorepassword = password
server.tlsport.truststore = etc/tls/truststore.p12
server.tlsport.truststorepassword = password

server.allowedclients = CN=client,OU=Test System CA,O=OpenSCDP,C=DE
