# Server configuration

scriptingserver.ports=mainport,adminport
scriptingserver.mainport.port=8080
scriptingserver.mainport.host=0.0.0.0
scriptingserver.adminport.port=8088
scriptingserver.adminport.host=0.0.0.0

scriptingserver.tls.keystore=etc/tls/clientkeystore.p12
scriptingserver.tls.keystorepassword=password
scriptingserver.tls.keystorekeypassword=password
scriptingserver.tls.truststore=etc/tls/truststore.p12
scriptingserver.tls.truststorepassword=password
