<?xml version="1.0" encoding="UTF-8"?>
<project name="pkiaas-backend-lab" xmlns:ivy="antlib:org.apache.ivy.ant" basedir="." default="resolve">

	<property name="major" value="1"/>
	<property name="minor" value="0"/>
	<property name="revision" value="0"/>	<!-- Set by jenkins -->
	<property name="version" value="${major}.${minor}.${revision}"/>
	<echo message="Version number is ${version}"/>

	<property name="shortname" value="${ant.project.name}"/>
	<property name="build" location="build"/>
	<property name="releasedir" location="released"/>

	<property name="publishresolver" value="local"/>

	<property name="deploymentscript" value="deploy-lab"/>
	<property name="deploymentargs" value="test.pki-as-a-service.net"/>

	<target name="ivyinit">
		<property name="ivy.settings.file" value="../ivysettings.xml" />
		<property name="ivy.settings.url" value="https://www.openscdp.org/ivy/ivysettings.xml" />
		<ivy:configure />
	</target>


	<target name="resolve" depends="ivyinit">
		<mkdir dir="${basedir}/lib"/>
		<ivy:retrieve pattern="[artifact].[ext]" type="tgz"/>
	</target>

	<target name="clean">
		<delete dir="${basedir}/lib"/>
		<delete dir="${basedir}/etc/tls"/>
		<delete dir="${basedir}/etc/tas"/>
		<delete dir="${basedir}/etc/template"/>
		<delete dir="${basedir}/bin"/>
		<delete dir="${basedir}/static"/>
		<delete file="${basedir}/start-service"/>
	</target>

</project>
